### ISSUE TITLE
INSTALL:9:*** missing separator.  STOP

### ISSUE THREAD

**Issue by aatendu** [gkudla/hyb#11]
I may be using the wrong makefile, because I get an error while trying to implement/install hyb

make -f INSTALL

produces:

INSTALL:9: *** missing separator.  STOP

Is this normal?

**Comment by tony-travis** [comment]
On 12/07/2024 09:17, Alexander Tendu wrote:
> I may be using the wrong makefile, because I get an error while trying 
> to implement/install hyb
> 
> make -f INSTALL
> 
> produces:
> 
> INSTALL:9: *** missing separator. STOP
> 
> Is this normal?

Hi, Alexander.

The default target of "make" is "Makefile" so there is no need to 
specify a file using "-f".

Bye,

   Tony.

-- 
Minke Informatics Limited, Registered in Scotland - Company No. SC419028
Registered Office: 3 Donview, Bridge of Alford, AB33 8QJ, Scotland (UK)
tel. +44(0)19755 63548                    http://minke-informatics.co.uk
mob. +44(0)7985 078324        ***@***.***

**Comment by aatendu** [comment]
Thank you for your swift response @Tony, but I am still unable to install hyb. Please advise on how I can do this. I'd really appreciate.

**Comment by aatendu** [comment]
ps. Linux terminal

**Comment by tony-travis** [comment]
Hi, Alexander.
What OS are your trying to install "hyb" onto?

**Comment by tony-travis** [comment]
It was developed under Ubuntu 20.04 LTS and you install it using:
git clone https://github.com/gkudla/hyb.git
cd hyb
sudo bash INSTALL

**Comment by tony-travis** [comment]
The confusion about "make" is that "hyb" is an executable Makefile, but I just wrote a "bash" script to install "hyb" and its dependencies. This should really have been done by packaging "hyb" properly for Debian/Ubuntu and although we started to do this with the Debian-Med team I wasn't able to meet the requirements for their "auto-package-test" system because of the size of the database files that would be required.

**Comment by aatendu** [comment]
Thanks Tony!

hyb is now running on my computer.

I am not running hyb with CLASH-type data, but are using it to identify chimeric NGS reads as I have found the .hyb summary quite useful. That's particularly for short reads (Illumina). However, It seems to me that I couldnt use hyb to identify chimeric reads in long-reads (ONT & Pacbio), because hyb produces either no hybrids (and I know this may reflect true absence of chimeras in long reads although not necessarily) or ...

Traceback (most recent call last):
  File "/home/tendu/hyb/bin/sam2blast", line 96, in <module>
    main(sys.argv[1])
  File "/home/tendu/hyb/bin/sam2blast", line 24, in main
    print_line(arr, 'f', dblen)
  File "/home/tendu/hyb/bin/sam2blast", line 73, in print_line
    mismatches = int([x for x in arr if x.startswith("NM:i:")]
IndexError: list index out of range

... with or without a list of chimeric reads as .hyb. I know this type of application for hyb may not necessarily be of interest to you. However, if you can think of a workaround for this task (finding chimeras in long reads), I'd be glad to hear it.

-Tendu

**Comment by gkudla** [comment]
Hi,

The problem seems to be with the script that converts the .sam file
produced by bowtie into an internal format used by hyb.

One of these could help as a workaround:

- use blast instead of bowtie as mapping engine (using align=blastall on
hyb command line)
OR
- remake the bowtie mapping database so that the gene names only contain
alphanumeric characters

Greg

**Comment by tony-travis** [comment]
I've just run "hyb" on the test data and "sam2blast" works fine using bowtie2-align-s version 2.4.4 under Ubuntu 22.04
```
root@beluga:/usr/local/hyb/data/fastq# hyb analyse in=testdata.txt db=hOH7 |& tee hyb.log
hyb: Fri 26 Jul 21:10:59 BST 2024
analyse
in=testdata.txt id=testdata format=fastq code= miss=0 qc=flexbar qual=33 link=TGGAATTCTCGGGTGCCAAGGC min=4 len=17 trim=0 filt=0 pc=0 align=bowtie2 db=hOH7 word=11 eval=0.1 ref= anti=0 type=all fold=UNAfold pref=mim hval=0.1 hmax=10 gmax=4
/usr/bin/flexbar -t testdata_clipped_qf -r testdata.txt  -as TGGAATTCTCGGGTGCCAAGGC -ao 4 -u 3 -m 17 -n 6
/usr/local/hyb/bin/solexa2fasta.awk testdata_clipped_qf.fastq | /usr/local/hyb/bin/fasta2tab.awk > testdata_clipped_qf.tab
/usr/local/hyb/bin/make_comp_fasta.pl testdata_clipped_qf.tab > testdata_comp.fasta
/usr/bin/bowtie2 -D 20 -R 3 -N 0 -L 16 -k 20 --local -i S,1,0.50 --score-min L,18,0 --ma 1 --np 0 --mp 2,2 --rdg 5,1 --rfg 5,1 -p 6 -x /usr/local/hyb/data/db/hOH7 -f testdata_comp.fasta > ./$$.sam 2> testdata_comp_hOH7.blast.err; \
sam2blast ./$$.sam > testdata_comp_hOH7.blast; \
rm ./$$.sam
rm testdata_comp_hOH7.blast.err
/usr/local/hyb/bin/mtophits_blast testdata_comp_hOH7.blast > testdata_comp_hOH7_mtophits.blast
/usr/local/hyb/bin/create_reference_file.pl testdata_comp_hOH7_mtophits.blast > testdata_comp_hOH7_mtophits.ref
/usr/local/hyb/bin/remove_duplicate_hits_blast.pl testdata_comp_hOH7_mtophits.ref testdata_comp_hOH7_mtophits.blast > testdata_comp_hOH7_singleE.blast
/usr/local/hyb/bin/blast_stats testdata_comp_hOH7_singleE.blast > testdata_comp_hOH7_singleE.blast_stats.txt
/usr/local/hyb/bin/get_mtop_hybrids.pl BLAST_THRESHOLD=0.1 MODE=2 MAX_OVERLAP=4 MAX_HITS_PER_SEQUENCE=10 OUTPUT_FORMAT=HYB testdata_comp_hOH7.blast > testdata_TEMP_FILE1_TXT
/usr/local/hyb/bin/getseqs testdata_TEMP_FILE1_TXT testdata_comp.fasta > testdata_comp_hOH7_hybrids.fasta
/usr/local/hyb/bin/fasta2tab.awk testdata_comp_hOH7_hybrids.fasta > testdata_TEMP_FILE1_TAB
/usr/local/hyb/bin/txt2hyb.awk testdata_TEMP_FILE1_TAB testdata_TEMP_FILE1_TXT > testdata_comp_hOH7_hybrids.hyb
/usr/local/hyb/bin/remove_duplicate_hybrids_hOH5.pl PREFER_MIM=1 testdata_comp_hOH7_mtophits.ref testdata_comp_hOH7_hybrids.hyb > testdata_comp_hOH7_hybrids_ua.hyb
/usr/local/hyb/bin/hyb2fasta_bits_allRNAs.awk /usr/local/hyb/data/db/hOH7.tab testdata_comp_hOH7_hybrids_ua.hyb
/usr/local/bin/hybrid-min testdata_comp_hOH7_hybrids_ua.bit_1.fasta testdata_comp_hOH7_hybrids_ua.bit_2.fasta 2>&1 > /dev/null
mv testdata_comp_hOH7_hybrids_ua.bit_1.fasta-testdata_comp_hOH7_hybrids_ua.bit_2.fasta.ct testdata_comp_hOH7_hybrids_ua.bit_1.fasta-comp_hOH7_hybrids_ua.bit_2.fasta.ct
rm testdata_comp_hOH7_hybrids_ua.bit_1.fasta-testdata_comp_hOH7_hybrids_ua.bit_2.fasta.run
rm testdata_comp_hOH7_hybrids_ua.bit_1.fasta-testdata_comp_hOH7_hybrids_ua.bit_2.fasta.37.plot
rm testdata_comp_hOH7_hybrids_ua.bit_1.fasta-testdata_comp_hOH7_hybrids_ua.bit_2.fasta.37.ext
rm testdata_comp_hOH7_hybrids_ua.bit_1.fasta-testdata_comp_hOH7_hybrids_ua.bit_2.fasta.dG
rm testdata_comp_hOH7_hybrids_ua.bit_1.fasta-testdata_comp_hOH7_hybrids_ua.bit_2.fasta.asc
/usr/local/hyb/bin/Ct2B_GK_3.pl testdata_comp_hOH7_hybrids_ua.bit_1.fasta-comp_hOH7_hybrids_ua.bit_2.fasta.ct > testdata_comp_hOH7_hybrids_ua.vienna
/usr/local/hyb/bin/add_dG_hyb.pl testdata_comp_hOH7_hybrids_ua.hyb testdata_comp_hOH7_hybrids_ua.vienna >testdata_comp_hOH7_hybrids_ua_dg.hyb
/usr/local/hyb/bin/combine_hyb_merge TWO_WAY_MERGE=1 PRINT_SEQ_IDS=1 testdata_comp_hOH7_hybrids_ua_dg.hyb > testdata_comp_hOH7_hybrids_ua_merged.hyb
/usr/local/hyb/bin/make_nicer_vienna_hOH5.awk testdata_comp_hOH7_hybrids_ua.vienna > testdata_comp_hOH7_hybrids_ua.viennad
/usr/local/hyb/bin/hybrid_stats testdata_comp_hOH7_hybrids_ua_dg.hyb > testdata_comp_hOH7_hybrids.hyb_stats.txt
rm testdata_TEMP_FILE1_TAB testdata_TEMP_FILE1_TXT testdata_comp_hOH7_hybrids_ua.bit_1.fasta-comp_hOH7_hybrids_ua.bit_2.fasta.ct
```
Tony.

**Comment by gkudla** [comment]
Yes sam2blast works on test data, but not on Tendu’s data. Hence the
workarounds I suggested.

Greg

**Comment by aatendu** [comment]
Thanks Greg!

The blastall option seems to work better for long reads. Much appreciated.

-Tendu
