### ISSUE TITLE
UNAfold

### ISSUE THREAD

**Issue by brobr** [gkudla/hyb#2]
Hi,

I just tried to install hyb on a mobile comp to be not so dependent on the university server and found:
a) when running the INSTALL script, hyb cannot find the path to its own installation in /usr/local/hyb/bin (this can be corrected by exporting this to $PATH before running the script again)
b) that a $200 academic license for UNAfold is needed to continue the installation (this is not in the software list of Biolinux 8). At the moment the script chokes on:
`/usr/local/hyb/bin/hyb:320: *** "hyb: UNAfold not installed".  Stop.` 
According to the hyb-script it seems that ViennaRNA could also be used. Would it be possible to alter the script so that it discovers which folding program is installed on a computer and can be used as the default? 
c) In relation to this, it would be helpful to list in a README file all the programs on which hyb depends for proper running and that have to be installed by the user beforehand (i.e. bowtie2, ViennaRNA/UNAfold, flexbar).

**Comment by tony-travis** [comment]
On 02/03/16 19:43, brobr wrote:
> Hi,
> 
> I just tried to install hyb on a mobile comp to be not so dependent on
> the university server and found:
> a) when running the INSTALL script, hyb cannot find the path to its own
> installation in /usr/local/hyb/bin (this can be corrected by exporting
> this to $PATH before running the script again)

Hi, brobr.

Thanks for reporting the issue: I've changed the INSTALL script to add
${HYB_HOME}/bin to the PATH for the test-run and output a message to say
you have to add ${HYB_HOME}/bin to your PATH after installation.

> b) that a $200 academic license for UNAfold is needed to continue the
> installation (this is not in the software list of Biolinux 8). At the
> moment the script chokes on:
> |/usr/local/hyb/bin/hyb:320: *** "hyb: UNAfold not installed". Stop.|
> According to the hyb-script it seems that ViennaRNA could also be used.
> Would it be possible to alter the script so that it discovers which
> folding program is installed on a computer and can be used as the default?

The error message is misleading: You don't need to install "UNAfold",
you just need to install the "bio-linux-oligoarrayaux" package, which
contains the "hybrid-min" program used by "hyb" for the default:

  fold=UNAfold

We prefer to keep "UNAfold" as the default, so I'll change the error
message to suggest installing the "bio-linux-oligoarrayaux" package.

> c) In relation to this, it would be helpful to list in a README file all
> the programs on which hyb depends for proper running and that have to be
> installed by the user beforehand (i.e. bowtie2, ViennaRNA/UNAfold, flexbar).

Quite right - I've been asked to do that several times already!

HTH,

  Tony.

-- 
Minke Informatics Limited, Registered in Scotland - Company No. SC419028
Registered Office: 3 Donview, Bridge of Alford, AB33 8QJ, Scotland (UK)
tel. +44(0)19755 63548                    http://minke-informatics.co.uk
mob. +44(0)7985 078324        mailto:tony.travis@minke-informatics.co.uk

**Comment by brobr** [comment]
Hi Tony,
Thanks for the quick and adequate response.
Installing the OligoArrayAux software from [ http://unafold.rna.albany.edu/?q=DINAMelt/OligoArrayAux ](url) worked (after adding it to the $PATH): the INSTALL script of Hyb ran to completion; the last line was:
`rm testdata_TEMP_FILE1_TXT testdata_TEMP_FILE1_TAB testdata_comp_hOH7_hybrids_ua.bit_1.fasta-comp_hOH7_hybrids_ua.bit_2.fasta.ct`
`bash-4.3#` 

Cheers,

Rob
