### ISSUE TITLE
the content of hyb file

### ISSUE THREAD

**Issue by junjieahaha** [gkudla/hyb#3]
Hello,
I have followed the article of 'Hyb:A bioinformatics pipeline for the analysis of CLASH data'.
I ran the hyb with the default parameter as the article presented.
hyb preprocess qc=flexbar trim=30 len=17 min=4 check detect align=bowtie2 word=11 ref=hg19_ensembl.gtf analyse fold=UNAfold in=123.fastq db=genome 
Whether it include 'ref=hg19_ensemble.gtf' the column 4 and column 10 in the hyb file is the chromosome number (example: chr1....chr10),not the gene name as the article presented(example:ACTB.....CCNB2).
So how to adjust the parameters  so that i could get the gene name in the hyb file instead of chromosome number.
Or is there any method that i could get the gene name through the coordinates.
One more question:Does 'count_total' in the column 16 of  hyb file represent the reads count of this gene? 
Thank you.

**Comment by gkudla** [comment]
The only way to have gene names, rather than chromosome names, in the hyb
file, is to map your fastq file against a transcriptome reference, rather
than genome reference. To map the reads against the transcriptome
reference, please use the "db=" command line option. You can use your own
transcriptome reference, but if you want to use the human transcriptome
reference distributed with hyb, please use "db=hOH7" on the command line.
"ref=" is an obscure option that you are unlikely to need.
Regarding the other question: count_total in column 16 of the
"*ua_merged.hyb" file represents the number of individual chimeric reads
the support the RNA-RNA interaction you're looking at.
Hope that helps,
Greg Kudla

**Comment by junjieahaha** [comment]
Thank you for your reply.
Is there more detailed instructions for the program? I still have some tiny questions.
Thanks.

**Comment by gkudla** [comment]
Here are some explanations written by Hywel Dunn-Davies from the Tollervey
lab. Hope that helps, but let me know if you have specific questions.

all the best,
Greg Kudla

---

1) Could you give us a description of the output files returned by the "hyb
detect" command?

Briefly, assuming an input file called data.fasta, a hyb database called
db, running the command 'hyb detect align=bowtie2 db=db format=comp
in=data.fasta' would give you the following files (listed in the order in
which they are generated):

data_comp_db.blast (generated by running bowtie2 on the fasta file, then
sam2blast on the output):
This is the basic alignment output file giving the alignment of all reads
against the database (including non-chimeric reads)

data_comp_db_mtophits.blast (generated by running mtophits_blast on the
blast file):
This is a filtered version of the blast file including only the most
significant hits (according to the e-value). If multiple hits are equally
significant they are all kept. As far as I know the script assumes that in
the blast output hits with the same sequence ID are ordered by e-value

data_comp_db_mtophits.ref (generated by running create_reference_data.pl on
the mtophits.blast file):
A reference data file containing a ranked list of genes, along with count
statistics (i.e. the total uncollapsed number of reads associated with each
gene / transcript, and the percentage of the total)

data_comp_db_singleE.blast (generated by running
remove_duplicate_hits_blast.pl on the mtophits ref file and blast file):
A filtered .blast file, with exactly one line per sequence ID

data_comp_db_singleE.blast_stats.txt (generated by running blast_stats on
the singleE blast file):
A text file containing the number of reads for each biotype

data_comp_db_hybrids.hyb (generated by get_mtop_hybrids.pl and some other
scripts):
A hyb file listing all of the hybrids, as described in the methods paper

data_comp_db_hybrids_ua.hyb (generated by running
remove_duplicate_hybrids_hOH5.pl on the hyb file):
A hyb file with duplicate hybrids removed

If you need more detail, I would suggest looking through the code of the
individual scripts. They are all in the bin folder of your hyb
installation, and can be opened with a text editor.

**Comment by junjieahaha** [comment]
Thank you.
