### ISSUE TITLE
paired end reads as input 

### ISSUE THREAD

**Issue by junjieahaha** [gkudla/hyb#4]
Can i use paired end fastq as input files?
Or i should probably merge two paired end fastq to a single fastq file?

**Comment by gkudla** [comment]
Yes, you should merge the two ends together before running hyb.

Greg

**Comment by junjieahaha** [comment]
Another question:how to skip the steps of preprocessing reads, for example, 
type in 'hyb detect align=bowtie2 in=data.fastq db=hOH7'
it will automatically completes to 'in=data.fastq id=data format=fastq code= miss=0 qc=flexbar qual=33 link=TGGAATTCTCGGGTGCCAAGGC min=4 len=17 trim=0 filt=0 pc=0 align=bowtie2 db=hOH7 word=11 eval=0.1 ref= anti=0 type=all fold=UNAfold pref=mim hval=0.1 hmax=10 gmax=4'. For the reads ars already clean data.

**Comment by gkudla** [comment]
try:
qc=none

**Comment by junjieahaha** [comment]
Thank you.  ^-^
