### ISSUE TITLE
flexbar: Too many arguments!

### ISSUE THREAD

**Issue by hrhotz** [gkudla/hyb#5]
Hi

I have just installed hyb together with the current version of flexbar (version: 3.4.0). When I run the test, I get the following error:

$ hyb analyse in=testdata.txt  db=hOH7
hyb: Wed Aug 15 15:03:53 CEST 2018
analyse
in=testdata.txt id=testdata format=fastq code= miss=0 qc=flexbar qual=33 link=TGGAATTCTCGGGTGCCAAGGC min=4 len=17 trim=0 filt=0 pc=0 align=bowtie2 db=hOH7 word=11 eval=0.1 ref= anti=0 type=all fold=UNAfold pref=mim hval=0.1 hmax=10 gmax=4
/***/flexbar -t testdata_clipped_qf -f sanger -r testdata.txt  -as TGGAATTCTCGGGTGCCAAGGC -ao 4 -u 3 -m 17 -n 24
flexbar: Too many arguments!

Available on github.com/seqan/flexbar

make: *** [testdata_clipped_qf.fastq] Error 1
$

As it turns out, the culprit is "-f sanger". According to the flexbar help, the "-f" option does not accept a string (any more?):

Output selection:
    -f, --fasta-output
          Prefer non-quality format fasta for output.

Which version of flexbar do you recommend to use?

Thank you very much for your help
Hans-Rudolf

**Comment by gkudla** [comment]
Hi Hans-Rudolf,

Thanks for reporting this!

hyb has been tested with flexbar versions 2.5 and 2.33. flexbar version 2.5 can be found here:
https://github.com/seqan/flexbar/releases/tag/v2.5.0

Hope that helps!
Greg

**Comment by tony-travis** [comment]
On 15/08/18 16:49, gkudla wrote:
> Hi Hans-Rudolf,
> 
> Thanks for reporting this!
> 
> hyb has been tested with flexbar versions 2.5 and 2.33. flexbar version
> 2.5 can be found here:
> https://github.com/seqan/flexbar/releases/tag/v2.5.0
> 
> Hope that helps!
> Greg

Hi, Hans-Rudolf and Greg.

The earlier versions of "flexbar" took a format string:

>     -f, --format STR
>           Quality format: sanger, solexa, i1.3, i1.5, i1.8 (illumina 1.8+).

Greg's suggestion of using "flexbar" 2.5 is the simplest work-around for
now until we update "hyb" to make it use the new version of "flexbar".

Bye,

  Tony.

-- 
Minke Informatics Limited, Registered in Scotland - Company No. SC419028
Registered Office: 3 Donview, Bridge of Alford, AB33 8QJ, Scotland (UK)
tel. +44(0)19755 63548                    http://minke-informatics.co.uk
mob. +44(0)7985 078324        mailto:tony.travis@minke-informatics.co.uk

**Comment by hrhotz** [comment]
Dear Greg and Tony

Thank you very much for your quick help

Regards, Hans-Rudolf

**Comment by williamtmills** [comment]
For those who might be curious, it is the `-as` parameter denoting the adapter sequence used in earlier versions of Flexbar but not in later versions that is causing the issue.
