### ISSUE TITLE
Documentation 

### ISSUE THREAD

**Issue by PriceJon** [gkudla/hyb#6]
In the Hyb paper it mentions that the output files are explained in the Hyb documentation, I feel like i'm missing something but I cannot seem to find this documentation. Sorry for the silly question. It is mainly for explanation of the difference between the *.hyb files.

**Comment by tony-travis** [comment]
On 25/07/2019 10:30, PriceJon wrote:
> In the Hyb paper it mentions that the output files are explained in the 
> Hyb documentation, I feel like i'm missing something but I cannot seem 
> to find this documentation. Sorry for the silly question. It is mainly 
> for explanation of the difference between the *.hyb files.

The Hyb manual is on GitHub:

> https://github.com/gkudla/hyb/blob/master/man/man1/hyb.1

One a system where "Hyb" is installed, you can view it using:

   man hyb

HTH,

   Tony.

-- 
Minke Informatics Limited, Registered in Scotland - Company No. SC419028
Registered Office: 3 Donview, Bridge of Alford, AB33 8QJ, Scotland (UK)
tel. +44(0)19755 63548                    http://minke-informatics.co.uk
mob. +44(0)7985 078324        mailto:tony.travis@minke-informatics.co.uk

**Comment by PriceJon** [comment]
Thanks for the prompt reply, 

I can't seem to find the explanation of the difference between the *_hybrids.hyb , *_hybrids_ua_dg.hyb  and the *_hybrids_ua.hyb files. Also why some of the chimeras in these files do not exist in the *_hybrids_ua_merged.hyb file. Again sorry for the basic questions I have checked the manual and paper but feel I maybe missing something. 

Thanks, 

Jon

**Comment by gkudla** [comment]
Dear Jon,

Thanks for your interest in this. Please find below an explanation of
the files generated by hyb. Most of the explanation is courtesy of
Hywel Dunn-Davies from the Tollervey lab. Hope that helps, let me know
if you have additional questions.

all the best,
Greg Kudla

---

1) Could you give us a description of the output files returned by the
"hyb detect" command?

Briefly, assuming an input file called data.fasta, a hyb database
called db, running the command 'hyb detect align=bowtie2 db=db
format=comp in=data.fasta' would give you the following files (listed
in the order in which they are generated):

data_comp_db.blast (generated by running bowtie2 on the fasta file,
then sam2blast on the output):
This is the basic alignment output file giving the alignment of all
reads against the database (including non-chimeric reads)

data_comp_db_mtophits.blast (generated by running mtophits_blast on
the blast file):
This is a filtered version of the blast file including only the most
significant hits (according to the e-value). If multiple hits are
equally significant they are all kept. As far as I know the script
assumes that in the blast output hits with the same sequence ID are
ordered by e-value

data_comp_db_mtophits.ref (generated by running
create_reference_data.pl on the mtophits.blast file):
A reference data file containing a ranked list of genes, along with
count statistics (i.e. the total uncollapsed number of reads
associated with each gene / transcript, and the percentage of the
total)

data_comp_db_singleE.blast (generated by running
remove_duplicate_hits_blast.pl on the mtophits ref file and blast
file):
A filtered .blast file, with exactly one line per sequence ID

data_comp_db_singleE.blast_stats.txt (generated by running blast_stats
on the singleE blast file):
A text file containing the number of reads for each biotype

data_comp_db_hybrids.hyb (generated by get_mtop_hybrids.pl and some
other scripts):
A hyb file listing all of the hybrids, as described in the methods paper

data_comp_db_hybrids_ua.hyb (generated by running
remove_duplicate_hybrids_hOH5.pl on the hyb file):
A hyb file with duplicate hybrids removed

data_comp_db_hybrids_ua_dg.hyb
A hyb file, same as *_ua.hyb, but with folding energy information added.
NOTE: this is the file I would typically use for downstream analysis

data_comp_db_hybrids_ua_merged.hyb
A hyb file, where the overlapping hybrids have been merged, similar to
the bedtools merge operation.

If you need more detail, I would suggest looking through the code of
the individual scripts. They are all in the bin folder of your hyb
installation, and can be opened with a text editor.

**Comment by PriceJon** [comment]
Thank you very much for the reply, that is fantastic, could you also extend my thanks to Hywel Dunn-Davies. All the best, 

Jon
